source 'https://rubygems.org'
ruby '2.2.2'

gem 'rails'
gem 'rspec'
gem 'dotenv-rails'
gem 'pg'
gem 'sass-rails'
gem 'sass'
gem 'uglifier'
gem 'coffee-rails'
gem 'dalli'
gem 'jquery-rails'
gem 'turbolinks', :git => 'https://github.com/rails/turbolinks.git'
gem 'jbuilder'
gem 'sdoc',          group: :doc
gem 'spring',        group: :development
gem 'foundation-rails'
gem 'gritter'
gem 'bullet', group: :development
gem 'rails-perftest'
gem 'ruby-prof'
gem 'bcrypt'
gem 'feedjira'
gem 'mobvious'
gem 'nokogiri'
gem 'htmlentities'
gem 'truncate_html'
gem 'jquery-turbolinks'
gem 'sitemap_generator'
gem 'fog'
gem 'carrierwave'
gem 'responders'
gem 'newrelic_rpm'
gem 'rollbar', '~> 2.1.1'
group :development do
  gem "rails-erd"
end
gem 'rack-mini-profiler'
gem 'thin'
